### ISSUE TITLE
Heroku is offline and lein doesn't run

### ISSUE THREAD

**Issue by metehan** [seabre/htmltohiccup#1]
```
D:\Dev\Clojure\htmltohiccup
λ lein run
Tried to use insecure HTTP repository without TLS:
 archive.org: http://builds.archive.org:8080/maven2
 org/mozilla/juniversalchardet/1.0.3/juniversalchardet-1.0.3.pom

This is almost certainly a mistake; for details see
https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md
```

**Comment by ignorabilis** [comment]
For future reference and to help with htmltohiccup not running/starting: downgrade `lein` to `2.7.1`, the version is not so strict, and run the project with it. If you get an exception like this one:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
...
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
```

you'll have to select an older jdk as well. To do so on Ubuntu:
``` bash
sudo update-alternatives --config java
```

**Comment by seabre** [comment]
Apologies on not being super responsive everybody. I'll re-open this and take a look.

**Comment by victorb** [comment]
Hello @seabre! No worries about the responsiveness, you're providing a free service :) And it's a great one, got so much value from it (using it for converting SVGs generated from Figma into Reagent components, works perfectly!)

Although, now when the Heroku app is offline, I wanted to run it locally, but didn't want to change anything about my existing environment (in fear of ruining it, I'm still not super used to Java stuff), so I added a Dockerfile + instructions for how to use it in this PR: https://github.com/seabre/htmltohiccup/pull/2

Took me about two minutes to add, so if you think it's overkill to add to this repository, no worries, just close the PR :)

Otherwise, thank you for the work on htmltohiccup! :+1:

**Comment by seabre** [comment]
Hey everybody,

I merged @victorb's PR which uses docker to make it easy to run this locally. I also investigated the Heroku issue and that is resolved now.

I'm really busy, but I'll work on upgrading dependencies and such so that this is easier to run and work on if you need to. Thanks!
